import Head from 'next/head';
import Layout from 'components/layout/layout.component';
import Post from 'components/post/post.component';
import { selectCurrentPost } from 'store/post/post.selector';
import { useSelector } from 'react-redux';
export default function Home() {
  const posts = useSelector(selectCurrentPost);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <>
          {posts &&
            posts.map((post: IPost, key: number) => {
              return <Post key={key} post={post} />;
            })}
        </>
      </Layout>
    </>
  );
}
